name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Runs a single command using the runners shell
    # - name: Install dependences
    #   run: |
    #     npm cache clear --force
    #     npm install

    # # Runs a single command using the runners shell
    # - name: Lerna bootstrap
    #   run: npm run bootstrap

    - name: Build queen
      run: |
        cd packages/queen
        npm install
        npm install eslint@6.8.0 --save-dev
        npm install eslint-plugin-vue@7.10.0 --save-dev
        npm install --save @dullar/cube
        npm run build

    - name: Move queen to root docs
      run: |
        mkdir docs
        mkdir docs/queen
        mv packages/queen/docs/* docs/queen
